### PR TITLE
Particles!

### PR DESCRIPTION
**Pull request by jbrennan**
tumblr_lhcsp6e5ba1qgjv7io1_250

Similar to https://github.com/Khan/Prototope/pull/9
- Adds a particles scene to the test app. Tap the cloud to make it rain!

### CODE REVIEW

**Comment by andymatuschak** [comment]
m-m-m-merge conflict!

Check out the new bits on OhaiPrototope in `SceneIndex.swift`!

**Comment by andymatuschak** [comment]
also omg where did you get that gif

**Comment by jbrennan** [comment]
> also omg where did you get that gif

My personal gif collection!

**Comment by jbrennan** [comment]
Also it seems like everything’s good to merge (initially there was a conflict though)

**Comment by andymatuschak** [comment]
Ah, looks like the merge is functionally fine but you added back a copy of the old `ViewController.swift` (now superseded by `SceneViewController.swift`)

**Pull request merged**
